services:
  # Backend API service
  - type: web
    name: mern-ecommerce-api
    env: node
    region: singapore  # Choose the region closest to your users
    plan: free  # Adjust based on your needs
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5002
      - key: MONGODB_URI
        sync: false  # This means you'll set it manually in the Render dashboard
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        fromService:
          name: mern-ecommerce-frontend
          type: web
          property: url
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
    healthCheckPath: /api/status
    
  # Frontend service
  - type: web
    name: mern-ecommerce-frontend
    env: node
    region: singapore  # Choose the region closest to your users
    plan: free  # Adjust based on your needs
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run preview
    envVars:
      - key: VITE_API_URL
        fromService:
          name: mern-ecommerce-api
          type: web
          property: url
      - key: VITE_APP_ENV
        value: production

# Configuration for secret environment variables
envVarGroups:
  - name: mern-ecommerce-secrets
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        # You will need to set this manually in the Render dashboard
        sync: false 